name: NPM publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20
      uses: actions/checkout@master
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
    - name: install depencencies 
      run: npm install
    - name: NPM publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}